### ISSUE TITLE
Consider proposing ES6 module

### ISSUE THREAD

**Issue by maximecolin** [NickPiscitelli/Glider.js#6]
I'm very happy to see a light lightweight lib without jquery, this is exactly what i'm looking for. Unfortunately there is no way to simply import it in a ES6 project. Do you plan to propose this lib as ES6 module ? This is the standard nowadays.

**Comment by NickPiscitelli** [comment]
Yes, definitely on the road map, as well as publishing to NPM and getting an official test suite. While I'm a big fan of ES6, I don't use it at my job and have little experience, but have been considering rewriting this whole project in ES6 for experience (or potentially TypeScript).

Happy to accept pull requests as well.

**Comment by NickPiscitelli** [comment]
This should be fixed now, let me know if there are any issues with it.

**Comment by hipstersmoothie** [comment]
I wrote a react wrapper around glider.js in typescript so i could throw you my interface ;) 

I still cannot import the library, only the global is working.

**Comment by hipstersmoothie** [comment]
@NickPiscitelli https://hipstersmoothie.com/react-glider/

https://github.com/hipstersmoothie/react-glider

**Comment by NickPiscitelli** [comment]
Wow, that's a really nice website you got there, I'm loving the playground.

I updated the module loader, I believe it should function properly now.

**Comment by hipstersmoothie** [comment]
I'll take a look. Any ETA on the npm module? imma start publishing once you do.

Heres what i used to build the playground. https://storybook.js.org/

The latest version support pure html/css i think, so you could potentially make one for this repo too

**Comment by NickPiscitelli** [comment]
That's neat, definitely going to take a look into Storybook.

I'm going to have the npm module done by this weekend, potentially tonight.
This is going to be my first module so I've just been reading up to make
sure I do it properly.

**Comment by NickPiscitelli** [comment]
Submitted. Now for updates, does npm automatically pull them from Github or
I need to re-publish to npm after any changes?

https://www.npmjs.com/package/glider-js

**Comment by ouuyeah** [comment]
Hi  and thanks to @NickPiscitelli for this great library, also to @hipstersmoothie for promote es6 and react into this.

By the way, any updates? I am waiting to use this in my react learning project :)

**Comment by hipstersmoothie** [comment]
I’ll try to get it released tonight!

**Comment by hipstersmoothie** [comment]
@ouuyeah have at it https://www.npmjs.com/package/react-glider

**Comment by bseib** [comment]
Is there a `glider-js.d.ts` file to import to typescript?

**Comment by NickPiscitelli** [comment]
There is not
